//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashRegisterRepairs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int ID { get; set; }
        public string SIM { get; set; }
        public string DEVICE_NUM_POSTFIX { get; set; }
        public string FISCAL_NUM_POSTFIX { get; set; }
        public string NAP_NUMBER { get; set; }
        public System.DateTime NAP_DATE { get; set; }
        public int MODEL_ID { get; set; }
        public int SITE_ID { get; set; }
    
        public virtual DeviceModel DeviceModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Site Site { get; set; }
    }
}
